### ISSUE TITLE
건물을 오브젝트로 추가하기

### ISSUE THREAD

**Issue by CoconutKR** [SerpensNebula/Korean-Town-Set#5]
한국 도시 세트를 잘 사용하고 있고 만들어 주셔서 감사합니다.
한가지 제안드릴것이 있어 이슈 제안드립니다.

한국 도시 세트의 건물을 오브젝트로도 건설할수있다면 어떨까 싶습니다.
한국 특유의 아파트 단지는 OpenTTD의 구조적 문제로 자연적으로 구현할수 없으니 오브젝트로도 등장한다면 좋을것 같다고 생각합니다.

번외로 스프라이트 제작과 관련해 질문드립니다.  1층은 6px로 찍으시는것으로 알고 있는데  6px 높이의 건물은 대략 몇m로 잡고 찍으시는지와 건물의 넓이 또한 px당 대략 몇m로 잡고 찍으시는지 궁금합니다.

**Comment by SerpensNebula** [comment]
> 한국 도시 세트를 잘 사용하고 있고 만들어 주셔서 감사합니다. 한가지 제안드릴것이 있어 이슈 제안드립니다.
> 
> 한국 도시 세트의 건물을 오브젝트로도 건설할수있다면 어떨까 싶습니다. 한국 특유의 아파트 단지는 OpenTTD의 구조적 문제로 자연적으로 구현할수 없으니 오브젝트로도 등장한다면 좋을것 같다고 생각합니다.
> 

생각은 있으나 계획은 아직 없습니다.

**Comment by SerpensNebula** [comment]
> 번외로 스프라이트 제작과 관련해 질문드립니다. 1층은 6px로 찍으시는것으로 알고 있는데 6px 높이의 건물은 대략 몇m로 잡고 찍으시는지와 건물의 넓이 또한 px당 대략 몇m로 잡고 찍으시는지 궁금합니다.

그런 기준은 없습니다. 단지 다른 건물grf들이 모두 최소 6px 이상으로 했기 때문에 따랐을 뿐입니다(건물에 따라 8~9px까지도 보였는데 5px 이하는 한국종합건물세트 제외 어디에도 없었습니다). 

그리고 그런식의 정량적인 현실 고증은 불가능합니다. 현실 크기 그대로 게임에 재현했다간 마천루 등의 높은 빌딩이 너무 커져버리는 문제가 생깁니다. 지금 구현되어있는 삼성전자 사옥이나 부산국제금융센터 등을 보시면 실제보다 대략 절반 이상 크기가 줄어들어 있습니다. 하지만 게임에서는 크게 부자연스럽지 않죠. 

현실 건물 재현도 중요하긴 하지만, _게임에서 어울리도록_ 만드는 것이 가장 먼저임을 알려드립니다. 다소의 수정과 창작은 불가피합니다.

**Comment by SerpensNebula** [comment]
옵젝 추가는 너무 방대한 작업이 될 것이기 때문에 이슈를 만든 의미가 없다고 판단하고 닫겠습니다.

**Comment by SerpensNebula** [comment]
오브젝트 grf를 만듦
