### ISSUE TITLE
[Bug] 저층 상가에 투명 스프라이트가 작업되어 있지 않음

### ISSUE THREAD

**Issue by JukjeonWani** [SerpensNebula/Korean-Town-Set#6]
![image](https://github.com/SerpensNebula/Korean-Town-Set/assets/88026704/491adf37-ea74-4816-99c2-9132895f6288)
![image](https://github.com/SerpensNebula/Korean-Town-Set/assets/88026704/7e4bb0c7-b22c-422e-87d3-de0d4095a4c1)

**Comment by SerpensNebula** [comment]
이미 0.4.0에서 고쳐졌습니다.
